# Each new term in the Fibonacci sequence is generated by adding the previous two
# terms. By starting with 1 and 2, the first 10 terms will be:
#
# 1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...
#
# By considering the terms in the Fibonacci sequence whose values do not exceed
# four million, find the sum of the even-valued terms.

def fibonaccis_upto(n)
  sequence = [1, 2]
  return sequence.take(n) if n <= 2

  next_fib = sequence[-1] + sequence[-2]
  until next_fib > n
    sequence << next_fib
    next_fib = sequence[-1] + sequence[-2]
  end

  sequence
end

if __FILE__ == $PROGRAM_NAME
  even_fibs = fibonaccis_upto(4 * (10 ** 6)).select! { |n| n % 2 == 0 }
  puts even_fibs.inject(&:+)
end
